# Generated by Django 6.0.2 on 2026-06-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0002_alter_tutorprofile_id_alter_tutorverification_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SIGNED", "Signed")],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("template_version", models.CharField(default="v1", max_length=20)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                ("signed_name", models.CharField(blank=True, default="", max_length=120)),
                ("signed_file", models.FileField(blank=True, null=True, upload_to="tutor_agreements/%Y/%m/")),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("tutor", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="tutor_agreement", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
