# Generated by Django 5.0.7 on 2026-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutorprofile_id_alter_tutorverification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutorverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
