# Generated by Django 5.0.7 on 2026-07-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_alter_availabilityslot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
