# Generated by Django 6.0.2 on 2026-06-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_subject_id_alter_tutorsubject_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("academic_level", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="course_thumbnails/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("PUBLISHED", "Published"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="courses", to="catalog.subject")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="courses", to=settings.AUTH_USER_MODEL)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("topic", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("video_file", models.FileField(blank=True, null=True, upload_to="lesson_videos/%Y/%m/")),
                ("video_url", models.URLField(blank=True, default="")),
                ("duration", models.PositiveIntegerField(blank=True, help_text="Duration in minutes", null=True)),
                ("order_number", models.PositiveIntegerField(default=1, db_index=True)),
                ("is_preview", models.BooleanField(default=False)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="catalog.course")),
            ],
            options={
                "ordering": ["course", "order_number", "created_at"],
                "unique_together": {("course", "order_number")},
            },
        ),
    ]
