# Generated by Django 6.0.2 on 2026-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_course_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorsubject",
            name="level",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30, choices=[
                ("PRIMARY", "Primary"),
                ("SECONDARY_LOWER", "Secondary Lower Level"),
                ("SECONDARY_UPPER", "Secondary Upper Level"),
                ("UNIVERSITY", "University"),
            ]),
        ),
    ]
