# Generated by Django 5.0.7 on 2026-06-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_tutorsubject_level_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_moderation_decisions', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_decisions', to='catalog.course')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
